### ISSUE TITLE
0.3.0 documentation changes

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/getkong.org#86]
A to-be-improved list of things to document for the upcoming 0.3.0, with links to possible documentation when available:

- [x] Admin API
  - [x]  New routes to document in the sidebar, `/plugins_configurations` should be considered deprecated in favour of `/apis/{api}/plugins` mashape/kong#257
  - [x] Update the tutorials to use the new routing (`/apis/{api}/plugins` and `/consumer/{consumer}/keyauth`) which will stop confusing users about the famous "API_ID" as a form parameter.
  - [x] It now supports `application/json` Content Type. mashape/kong#236
  - [x] It now supports `PUT` calls. mashape/kong#236
- [ ] Proxy
  - [ ] Support for path routing. mashape/kong#282
  - [ ] Support for alternate Host header: `X-Host-Override`. mashape/kong#246
  - [x] Headers sent to the upstream server when using authentication plugins
- [x] Plugins
  - [x] HTTP logging docs. mashape/kong#244
  - [x] File logging has a new option to specify a path to a file. mashape/kong#202
  - [x] Document the SSL plugin, and SSL features. mashape/kong#254
  - ~~Document the Analytics plugin. mashape/kong#272~~
  - [x] Document the response transformations plugin.
  - [x] Document the request size limiting plugin
- [ ] Chore
  - [ ] Document that openresty must be patched in the Source install for SSL support

---
Not related to 0.3.0, but still missing
- [x] Document the default logging format.
- [ ] Document how the proxy layer works. #80 Also related to the new path routing and the new `X-Host-Override` header.

**Comment by sinzone** [comment]
Size payload plugin?

**Comment by thibaultCha** [comment]
Who removed the important comments that were posted below this? With the summary of how to document the Proxy layer? -_-

**Comment by thibaultCha** [comment]
#80 + #89
